/**
 * PDF export utility using jsPDF.
 * Generates a formatted report of the video analysis.
 */

import type { AnalysisResponse, RiskScores } from "../types";

export async function exportToPdf(
  analysis: AnalysisResponse,
  videoTitle: string
): Promise<void> {
  // Dynamically import jsPDF to keep bundle size small
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text("SafeTube AI Report", margin, y);
  y += 12;

  // Video title
  doc.setFontSize(12);
  doc.setTextColor(71, 85, 105); // slate-500
  const titleLines = doc.splitTextToSize(videoTitle, pageWidth - 2 * margin);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 6 + 8;

  // Divider
  doc.setDrawColor(203, 213, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Age Rating
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text("Recommended Age", margin, y);
  doc.setFontSize(28);
  doc.setTextColor(getAgeColor(analysis.recommended_age));
  doc.text(`${analysis.recommended_age}+`, pageWidth - margin - 30, y);
  y += 14;

  // Confidence
  doc.setFontSize(12);
  doc.setTextColor(71, 85, 105);
  doc.text(`Confidence: ${analysis.confidence.toFixed(1)}%`, margin, y);
  y += 12;

  // Divider
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Risk Scores
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Risk Scores", margin, y);
  y += 8;

  const categories: { key: keyof RiskScores; label: string }[] = [
    { key: "violence", label: "Violence" },
    { key: "profanity", label: "Profanity" },
    { key: "sexual_content", label: "Sexual Content" },
    { key: "drugs", label: "Drugs" },
    { key: "hate_speech", label: "Hate Speech" },
    { key: "scary_content", label: "Fear / Horror" },
  ];

  doc.setFontSize(11);
  for (const cat of categories) {
    const score = analysis.risk_scores[cat.key];
    doc.setTextColor(71, 85, 105);
    doc.text(cat.label, margin + 4, y);
    doc.setTextColor(15, 23, 42);
    doc.text(`${score.toFixed(1)}%`, pageWidth - margin - 20, y);

    // Progress bar background
    const barX = margin + 60;
    const barWidth = pageWidth - margin - 60 - 30;
    doc.setFillColor(226, 232, 240);
    doc.roundedRect(barX, y - 3, barWidth, 4, 2, 2, "F");

    // Progress bar fill
    const fillColor = score > 60 ? [239, 68, 68] : score > 30 ? [249, 115, 22] : [34, 197, 94];
    doc.setFillColor(fillColor[0], fillColor[1], fillColor[2]);
    doc.roundedRect(barX, y - 3, (barWidth * score) / 100, 4, 2, 2, "F");

    y += 8;
  }

  y += 4;

  // Educational Score
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Educational Score", margin, y);
  doc.setFontSize(16);
  doc.setTextColor(34, 197, 94);
  doc.text(`${analysis.educational_score.toFixed(1)}%`, pageWidth - margin - 25, y);
  y += 14;

  // Summary
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("AI Summary", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  const summaryLines = doc.splitTextToSize(analysis.summary, pageWidth - 2 * margin);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 6 + 10;

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated by SafeTube AI on ${new Date().toLocaleDateString()}`,
    margin,
    doc.internal.pageSize.getHeight() - 10
  );

  // Save
  const safeTitle = videoTitle.replace(/[^a-z0-9]/gi, "_").substring(0, 40);
  doc.save(`safetube_report_${safeTitle}.pdf`);
}

function getAgeColor(age: number): string {
  if (age <= 3) return "#22c55e";
  if (age <= 7) return "#84cc16";
  if (age <= 10) return "#eab308";
  if (age <= 13) return "#f97316";
  if (age <= 16) return "#ef4444";
  return "#dc2626";
}
